### ISSUE TITLE
new patch heliwrt and helmi lib patch

### ISSUE THREAD

**Issue by latiefkhan** [helmiau/HelmiWrt-OS#29]
the patch of  helmilib and helmiwrt patch always running when boot, and always make new interface and adding so many interface. including adding MWAN3 and multiple firewall in everytime boot

**Comment by helmiau** [comment]
> the patch of helmilib and helmiwrt patch always running when boot, and always make new interface and adding so many interface. including adding MWAN3 and multiple firewall in everytime boot

any screenshot or log?

**Comment by latiefkhan** [comment]
> > the patch of helmilib and helmiwrt patch always running when boot, and always make new interface and adding so many interface. including adding MWAN3 and multiple firewall in everytime boot
> 
> any screenshot or log?

Sorry, i don't have, because i've been deleted thats 3 file of patch this firmware, and problem solved. 
Helmilib, helmilib2 and helmiwrt file on in bin folder

**Comment by latiefkhan** [comment]
But the problem will not havent, if we does not deleting any interface on Network, or changing MWAN3 settings.

**Comment by helmiau** [comment]
i think, your case happend because you editing default interface & firewall name or deleting it.

**Comment by latiefkhan** [comment]
> i think, your case happend because you editing default interface & firewall name or deleting it.
> 
> **if you have any problems soon, please post a issue with log or screenshot**. thank's

Yes i did that, editing and deleting, i know why this firmware did this to me, because this firmware is exclusive for loadbalancing purpose.!

**Comment by helmiau** [comment]
> > i think, your case happend because you editing default interface & firewall name or deleting it.
> > **if you have any problems soon, please post a issue with log or screenshot**. thank's
> 
> Yes i did that, editing and deleting, i know why this firmware did this to me, because this firmware is exclusive for loadbalancing purpose.!

this problem should'nt occur on tomorrow builds hopefully. Cause i separate loadbalance configurations

**Comment by latiefkhan** [comment]
> > > i think, your case happend because you editing default interface & firewall name or deleting it.
> > > **if you have any problems soon, please post a issue with log or screenshot**. thank's
> > 
> > 
> > Yes i did that, editing and deleting, i know why this firmware did this to me, because this firmware is exclusive for loadbalancing purpose.!
> 
> this problem should'nt occur on tomorrow builds hopefully. Cause i separate loadbalance configurations

Thank you so much for your quick reply, that was make me so proud of your work.
