### ISSUE TITLE
Can I get a clean software firmware

### ISSUE THREAD

**Issue by carlocensi813** [helmiau/HelmiWrt-OS#49]
Hi, this is the first openwrt firmware I found that works with my hardware amlogic "s905". I installed this version "helmiwrt-s905x-k5.4.150.img.gz". 

Can I get a cleaner IMG? just with luci, basic software and drivers? I don't need most of the software that's already installed. Thank you.

PD: I know that there are another repositories like ophub, I tried ophub s905x  5.4.163, but that one just give reboot on a loop. Your firmware is the only one I found that it works

**Comment by helmiau** [comment]
sorry, there is no clean or minimal even lite firmware. due to my blog explained that this firmware is ready to use.
